{
 "title": "rchm",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Node 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Memory usage", "gridPos": { "h": 9, "w": 16, "x": 0, "y": 1 } },
  {
   "title": "Memory Use Percent",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_memory_usage", "legendFormat": "__auto" }
   ]
  },
  { "title": "CPU usage", "gridPos": { "h": 8, "w": 16, "x": 0, "y": 10 } },
  { "title": "CPU usage percent", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 } },
  { "title": "CPU Frequency", "gridPos": { "h": 8, "w": 16, "x": 0, "y": 18 } },
  {
   "title": "CPU frequency clock",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_CPU_MHz", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Processes",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "targets": [
    { "expr": "system_process_info", "legendFormat": "__auto" }
   ]
  },
  { "title": "PCI Information", "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 } },
  { "title": "USB Information", "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 } },
  { "title": "Disk Information", "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 } }
 ]
}