= host-agent-core
:toc:

Conceptually this sysinfo application is based around the core functionality.

== Classes
=== Sysinfo
This class serves as the entrypoint class for the application.

Currently, the interface for the Sysinfo class is being created, but as of now the available methods are:

[source, java]
----
interface SysinfoInterface {
    ArrayList<Integer> getRunningPIDs();
    ProcessInfo getProcessInfo(int pid);
    SystemMemoryInfo getSystemMemoryInfo();
}
----

=== ProcessInfo

==== Properties
Reads the /proc/<pid>/status virtual file to return a class with properties such as

- _name_ (the name of the process)
- _pid_ (the process ID number)
- _ppid_ (the pid of this process' parent)
- _state_ (the state of the process, which can be one of 5 process states: _RUN_, _SLEEP_, _UNINTERRUPTABLE_SLEEP_, _STOPPED_, _ZOMBIE_)

==== Methods

Has methods to get global system information, such as the PIDs of all running processes on the host:

=== MetricServer
This class starts a server at the specified IP and port which exposes the metrics for get requests at <the specified IP>:<port>/metrics

==== Methods
The start() method starts the HttpServer and starts 2 threads that constantly update the prometheus gauges.

